In [2]:
#import pandas
import pandas as pd

In [3]:
#create a list of data
data = [1, 2, 3, 4, 5, 7, 10]
data

[1, 2, 3, 4, 5, 7, 10]

In [4]:
type(data)

list

### Series

In [5]:
#create a series from the list
s = pd.Series(data)
s

0     1
1     2
2     3
3     4
4     5
5     7
6    10
dtype: int64

In [6]:
type(s)

pandas.Series

In [7]:
data

[1, 2, 3, 4, 5, 7, 10]

###  DataFrame

In [8]:
#create DataFrame from data
df = pd.DataFrame(data, columns=["Numbers"])
df

   Numbers
0        1
1        2
2        3
3        4
4        5
5        7
6       10

In [9]:
#create DataFrame from the series
df = pd.DataFrame(s, columns=['Numbers'])
df

   Numbers
0        1
1        2
2        3
3        4
4        5
5        7
6       10

In [10]:
#create a series from 2 integers columns
data_2 = [[1, 2],[3, 4],[5, 6],[7, 8],[1, 9]]
data_2

[[1, 2], [3, 4], [5, 6], [7, 8], [1, 9]]

In [11]:
#create a DataFrame from data_2
df_2 = pd.DataFrame(data_2, columns=['col_1', 'col_2'])
df_2

   col_1  col_2
0      1      2
1      3      4
2      5      6
3      7      8
4      1      9

In [12]:
#create a Series from the DataFrame(df_2)
s_1 = pd.Series(df_2['col_1'])
s_1

0    1
1    3
2    5
3    7
4    1
Name: col_1, dtype: int64

### Dictionary to Series & DataFrame

In [13]:
#Create a Dictionary
members = {
    "Name": ["John", "Jane", "Jack", "Jill"],
    "Age": [26, 24, 22, 28],
    "City": ["Berlin", "London", "Moscow", "New York"]
}

In [14]:
members

{'Name': ['John', 'Jane', 'Jack', 'Jill'],
 'Age': [26, 24, 22, 28],
 'City': ['Berlin', 'London', 'Moscow', 'New York']}

In [15]:
#create a Series from the dictionary
s = pd.Series(members)
s

Name              [John, Jane, Jack, Jill]
Age                       [26, 24, 22, 28]
City    [Berlin, London, Moscow, New York]
dtype: object

In [16]:
#create a series from the dictionary with only the "Name" key
s = pd.Series(members["Name"])
s

0    John
1    Jane
2    Jack
3    Jill
dtype: str

In [17]:
#create a DataFrame from the dictionary
df = pd.DataFrame(members)
df

   Name  Age      City
0  John   26    Berlin
1  Jane   24    London
2  Jack   22    Moscow
3  Jill   28  New York

### Set to Series and DataFrame

In [26]:
set1 = {1, 2, 3, 4, 5}

print(set1)
type(set1)

{1, 2, 3, 4, 5}

set

In [27]:
#create a series from the set
series = pd.Series(list(set1))
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [29]:
#create a DataFrame from the set
df = pd.DataFrame(list(set1), columns=['Set_Values'])
df

   Set_Values
0           1
1           2
2           3
3           4
4           5

### Tuple to Series and DataFrame

In [33]:
t = (1, 2, 3, 4, 5, True)
print(t)
type(t)

(1, 2, 3, 4, 5, True)

tuple

In [34]:
series = pd.Series(list(t))
series

0       1
1       2
2       3
3       4
4       5
5    True
dtype: object

In [35]:
df = pd.DataFrame(list(t), columns=["Tuple_Values"])
df

  Tuple_Values
0            1
1            2
2            3
3            4
4            5
5         True