# Pandas Numeric Data Types

| **Data Type** | **Description**                                                       | **Common Pandas dtypes**          |
| ------------- | --------------------------------------------------------------------- | --------------------------------- |
| **Integer**   | Integer data types store whole numbers such as `-1`, `10`, and `100`. | `int8`, `int16`, `int32`, `int64` |
| **Float**     | Float data types store numbers that can contain decimal values.       | `float16`, `float32`, `float64`   |

---

# Pandas Integer Data Types — Range of Values

| **Data Type** | **Size (bits)** | **Size (bytes)** | **Range of Values**                                     | **Range Formula** |
| ------------- | --------------: | ---------------: | ------------------------------------------------------- | ----------------- |
| `int8`        |               8 |                1 | -128 to 127                                             | −2⁷ to 2⁷ − 1     |
| `int16`       |              16 |                2 | -32,768 to 32,767                                       | −2¹⁵ to 2¹⁵ − 1   |
| `int32`       |              32 |                4 | -2,147,483,648 to 2,147,483,647                         | −2³¹ to 2³¹ − 1   |
| `int64`       |              64 |                8 | -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807 | −2⁶³ to 2⁶³ − 1   |

---

# Additional Pandas Data Types

| **Category**      | **Data Type** | **Description**                                                                                  | **Common Pandas dtype** |
| ----------------- | ------------- | ------------------------------------------------------------------------------------------------ | ----------------------- |
| **Date and Time** | Timestamp     | Represents dates and times.                                                                      | `datetime64[ns]`        |
| **Date and Time** | Timedelta     | Represents differences or durations between dates and times.                                     | `timedelta64[ns]`       |
| **Categorical**   | Category      | Represents data with a finite number of categories. Useful for **nominal** and **ordinal** data. | `category`              |
| **Text**          | String        | Represents text data.                                                                            | `string` / `object`     |
| **Boolean**       | Boolean       | Represents logical values such as **True** and **False**.                                        | `bool` / `boolean`      |

In [66]:
import pandas as pd

In [67]:
#create a DataFrame with numeric data
data ={"age":[23, 45, 56, 25, 34, 65, 20, 30, 40, 45],
       "salary":[10000, 20000, 30000, 40000, 50000, 60000, 70000, 80000, 90000, 100000]}
df = pd.DataFrame(data)
df

   age  salary
0   23   10000
1   45   20000
2   56   30000
3   25   40000
4   34   50000
5   65   60000
6   20   70000
7   30   80000
8   40   90000
9   45  100000

In [68]:
# Get the data types of each column in the Dataframe
df.dtypes

age       int64
salary    int64
dtype: object

In [69]:
# changing the data type of each column in the DataFrame 
df['age'] = df['age'].astype('int32')
df['salary'] = df['salary'].astype('float32')
df

   age    salary
0   23   10000.0
1   45   20000.0
2   56   30000.0
3   25   40000.0
4   34   50000.0
5   65   60000.0
6   20   70000.0
7   30   80000.0
8   40   90000.0
9   45  100000.0

In [70]:
df.dtypes

age         int32
salary    float32
dtype: object

In [71]:
# create a DataFrame with mixed data types
data ={"Name":['john', 'jane', 'jack', 'jill', 'jim', 'joe', 'jerry', 'jessica', 'jasmine', 'jordan'],
       "age":[23, 45, 56, 25, 34, 65, 20, 30, 40, 45],
       "ocupation":['Data Scientist', 'Data Analyst', 'Data Engineer', 'Data Architect', 'Data Manager', 
                    'Data consultant','Software Engineer', 'Software Developer', 'MIS Analyst', 'Business Analyst'],
       "salary":[10000, 20000, 30000, 40000, 50000, 60000, 70000, 80000, 90000, 100000]}
df1 = pd.DataFrame(data)
df1

      Name  age           ocupation  salary
0     john   23      Data Scientist   10000
1     jane   45        Data Analyst   20000
2     jack   56       Data Engineer   30000
3     jill   25      Data Architect   40000
4      jim   34        Data Manager   50000
5      joe   65     Data consultant   60000
6    jerry   20   Software Engineer   70000
7  jessica   30  Software Developer   80000
8  jasmine   40         MIS Analyst   90000
9   jordan   45    Business Analyst  100000

In [72]:
df.dtypes

age         int32
salary    float32
dtype: object

### Datetime

In [73]:
#create a list of dates
dates = ['2026', '2026', '2026', '2026', '2026']
#create a DataFrame with date data
df1 =pd.DataFrame(dates, columns=['date'])
df1

   date
0  2026
1  2026
2  2026
3  2026
4  2026

In [74]:
df1.dtypes

date    str
dtype: object

In [75]:
#convert the data column to datetime format
timestamps = pd.to_datetime(df1['date'])
timestamps

0   2026-01-01
1   2026-01-01
2   2026-01-01
3   2026-01-01
4   2026-01-01
Name: date, dtype: datetime64[us]

In [76]:
#create a DataFrame with the converted datetime data
df2 = pd.DataFrame({'dates': timestamps})
df2

       dates
0 2026-01-01
1 2026-01-01
2 2026-01-01
3 2026-01-01
4 2026-01-01

In [77]:
df2.dtypes

dates    datetime64[us]
dtype: object

In [79]:
#create a list of dates with time information
dates2 = ['2026-01-01 12:01:26.1215', '2026-02-01 12:02:25.5456', '2026-03-02 12:03:24.9897']

timestamps = pd.to_datetime(dates2)
df3 = pd.DataFrame({'dates': timestamps})
df3

                       dates
0 2026-01-01 12:01:26.121500
1 2026-02-01 12:02:25.545600
2 2026-03-02 12:03:24.989700

In [81]:
df3['dates'].dtypes

dtype('<M8[us]')